FROM node:20 AS base

#Add environmental variables
ARG GOOGLE_ID
ARG GOOGLE_SECRET
ARG GITHUB_ID
ARG GITHUB_SECRET
ARG MONGODB_URI
ARG NEXTAUTH_SECRET
ARG NEXTAUTH_URL

ENV GOOGLE_ID $GOOGLE_ID
ENV GOOGLE_SECRET $GOOGLE_SECRET
ENV GITHUB_ID $GITHUB_ID
ENV GITHUB_SECRET $GITHUB_SECRET
ENV MONGODB_URI $MONGODB_URI
ENV NEXTAUTH_SECRET $NEXTAUTH_SECRET
ENV NEXTAUTH_URL $NEXTAUTH_URL

# Stage 1: Build the NextJs app
FROM base AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Stage 2: Serve the app
FROM base AS runtime
WORKDIR /app
COPY --from=build /app/ .
EXPOSE 3000
USER node
CMD ["npm", "start"]