FROM node:20

WORKDIR /usr/src/app

#Add environmental variables
ARG NEXT_PUPLIC_APP_BASE_URL
ARG GOOGLE_ID
ARG GOOGLE_SECRET
ARG GITHUB_ID
ARG GITHUB_SECRET
ARG MONGODB_URI

ENV NEXT_PUPLIC_APP_BASE_URL $NEXT_PUPLIC_APP_BASE_URL
ENV GOOGLE_ID $GOOGLE_ID
ENV GOOGLE_SECRET $GOOGLE_SECRET
ENV GITHUB_ID $GITHUB_ID
ENV GITHUB_SECRET $GITHUB_SECRET
ENV MONGODB_URI $MONGODB_URI

COPY package*.json ./
RUN npm install

COPY . .
EXPOSE 3000
CMD ["npm", "run", "build"]
