name: Deploy to Amazon ECS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ${{ vars.AWS_REGION }}                  
  ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}           
  ECS_SERVICE: ${{ vars.ECS_SERVICE }}                 
  ECS_CLUSTER: ${{ vars.ECS_CLUSTER }}                
  ECS_TASK_DEFINITION: ${{ vars.ECS_TASK_DEFINITION }} 
  CONTAINER_NAME: ${{ vars.CONTAINER_NAME }}
  NEXTAUTH_URL: ${{ vars.NEXTAUTH_URL }}
  GOOGLE_ID: ${{ secrets.GOOGLE_ID }}
  GOOGLE_SECRET: ${{ secrets.GOOGLE_SECRET }}
  GITHUB_ID: ${{ secrets.OAUTH_GITHUB_ID }}
  GITHUB_SECRET: ${{ secrets.OAUTH_GITHUB_ID }}
  MONGODB_URI: ${{ secrets.MONGODB_URI }}
  NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Save Cache
        id: cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: install

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Lint app
        run: npm run lint

  test:
    name: Test
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Save Cache
        id: cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: install

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Test app using Cypress.io
        uses: cypress-io/github-action@v6.6.1
        with:
          build: yarn build
          start: yarn start
          wait-on: "http://localhost:3000"
  
  scan: 
    name: Scan
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Save Cache
        id: cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: install

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Scan app
        run: npm audit

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    needs: [lint, test, scan]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2.0.1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        uses: docker/build-push-action@v5
        with: 
          context: .
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}     
          build-args: |
            GOOGLE_ID=${{ secrets.GOOGLE_ID }}
            GOOGLE_SECRET=${{ secrets.GOOGLE_SECRET }}
            GITHUB_ID=${{ secrets.OAUTH_GITHUB_ID }}
            GITHUB_SECRET=${{ secrets.OAUTH_GITHUB_ID }}
            MONGODB_URI=${{ secrets.MONGODB_URI }}
            NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}
            NEXTAUTH_URL=${{ env.NEXTAUTH_URL }}

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1.2.0
        with:
          task-definition: ${{ env.ECS_TASK_DEFINITION }}
          container-name: ${{ env.CONTAINER_NAME }}
          image: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1.4.11
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true
